# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ankush/Ankush/OpenGL

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ankush/Ankush/OpenGL

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ankush/Ankush/OpenGL/CMakeFiles /home/ankush/Ankush/OpenGL//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ankush/Ankush/OpenGL/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named project

# Build rule for target.
project: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 project
.PHONY : project

# fast build rule for target.
project/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/build
.PHONY : project/fast

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) $(MAKESILENT) -f include/imgui/CMakeFiles/imgui.dir/build.make include/imgui/CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

src/Buffer/Buffer.o: src/Buffer/Buffer.cpp.o
.PHONY : src/Buffer/Buffer.o

# target to build an object file
src/Buffer/Buffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/Buffer/Buffer.cpp.o
.PHONY : src/Buffer/Buffer.cpp.o

src/Buffer/Buffer.i: src/Buffer/Buffer.cpp.i
.PHONY : src/Buffer/Buffer.i

# target to preprocess a source file
src/Buffer/Buffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/Buffer/Buffer.cpp.i
.PHONY : src/Buffer/Buffer.cpp.i

src/Buffer/Buffer.s: src/Buffer/Buffer.cpp.s
.PHONY : src/Buffer/Buffer.s

# target to generate assembly for a file
src/Buffer/Buffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/Buffer/Buffer.cpp.s
.PHONY : src/Buffer/Buffer.cpp.s

src/Global/Scene.o: src/Global/Scene.cpp.o
.PHONY : src/Global/Scene.o

# target to build an object file
src/Global/Scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/Global/Scene.cpp.o
.PHONY : src/Global/Scene.cpp.o

src/Global/Scene.i: src/Global/Scene.cpp.i
.PHONY : src/Global/Scene.i

# target to preprocess a source file
src/Global/Scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/Global/Scene.cpp.i
.PHONY : src/Global/Scene.cpp.i

src/Global/Scene.s: src/Global/Scene.cpp.s
.PHONY : src/Global/Scene.s

# target to generate assembly for a file
src/Global/Scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/Global/Scene.cpp.s
.PHONY : src/Global/Scene.cpp.s

src/Meshes/ManualMesh.o: src/Meshes/ManualMesh.cpp.o
.PHONY : src/Meshes/ManualMesh.o

# target to build an object file
src/Meshes/ManualMesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/Meshes/ManualMesh.cpp.o
.PHONY : src/Meshes/ManualMesh.cpp.o

src/Meshes/ManualMesh.i: src/Meshes/ManualMesh.cpp.i
.PHONY : src/Meshes/ManualMesh.i

# target to preprocess a source file
src/Meshes/ManualMesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/Meshes/ManualMesh.cpp.i
.PHONY : src/Meshes/ManualMesh.cpp.i

src/Meshes/ManualMesh.s: src/Meshes/ManualMesh.cpp.s
.PHONY : src/Meshes/ManualMesh.s

# target to generate assembly for a file
src/Meshes/ManualMesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/Meshes/ManualMesh.cpp.s
.PHONY : src/Meshes/ManualMesh.cpp.s

src/Objects/Drawable.o: src/Objects/Drawable.cpp.o
.PHONY : src/Objects/Drawable.o

# target to build an object file
src/Objects/Drawable.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/Objects/Drawable.cpp.o
.PHONY : src/Objects/Drawable.cpp.o

src/Objects/Drawable.i: src/Objects/Drawable.cpp.i
.PHONY : src/Objects/Drawable.i

# target to preprocess a source file
src/Objects/Drawable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/Objects/Drawable.cpp.i
.PHONY : src/Objects/Drawable.cpp.i

src/Objects/Drawable.s: src/Objects/Drawable.cpp.s
.PHONY : src/Objects/Drawable.s

# target to generate assembly for a file
src/Objects/Drawable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/Objects/Drawable.cpp.s
.PHONY : src/Objects/Drawable.cpp.s

src/Shaders/ShaderProgram.o: src/Shaders/ShaderProgram.cpp.o
.PHONY : src/Shaders/ShaderProgram.o

# target to build an object file
src/Shaders/ShaderProgram.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/Shaders/ShaderProgram.cpp.o
.PHONY : src/Shaders/ShaderProgram.cpp.o

src/Shaders/ShaderProgram.i: src/Shaders/ShaderProgram.cpp.i
.PHONY : src/Shaders/ShaderProgram.i

# target to preprocess a source file
src/Shaders/ShaderProgram.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/Shaders/ShaderProgram.cpp.i
.PHONY : src/Shaders/ShaderProgram.cpp.i

src/Shaders/ShaderProgram.s: src/Shaders/ShaderProgram.cpp.s
.PHONY : src/Shaders/ShaderProgram.s

# target to generate assembly for a file
src/Shaders/ShaderProgram.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/Shaders/ShaderProgram.cpp.s
.PHONY : src/Shaders/ShaderProgram.cpp.s

src/Textures/FrameBuffer.o: src/Textures/FrameBuffer.cpp.o
.PHONY : src/Textures/FrameBuffer.o

# target to build an object file
src/Textures/FrameBuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/Textures/FrameBuffer.cpp.o
.PHONY : src/Textures/FrameBuffer.cpp.o

src/Textures/FrameBuffer.i: src/Textures/FrameBuffer.cpp.i
.PHONY : src/Textures/FrameBuffer.i

# target to preprocess a source file
src/Textures/FrameBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/Textures/FrameBuffer.cpp.i
.PHONY : src/Textures/FrameBuffer.cpp.i

src/Textures/FrameBuffer.s: src/Textures/FrameBuffer.cpp.s
.PHONY : src/Textures/FrameBuffer.s

# target to generate assembly for a file
src/Textures/FrameBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/Textures/FrameBuffer.cpp.s
.PHONY : src/Textures/FrameBuffer.cpp.s

src/Textures/Texture.o: src/Textures/Texture.cpp.o
.PHONY : src/Textures/Texture.o

# target to build an object file
src/Textures/Texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/Textures/Texture.cpp.o
.PHONY : src/Textures/Texture.cpp.o

src/Textures/Texture.i: src/Textures/Texture.cpp.i
.PHONY : src/Textures/Texture.i

# target to preprocess a source file
src/Textures/Texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/Textures/Texture.cpp.i
.PHONY : src/Textures/Texture.cpp.i

src/Textures/Texture.s: src/Textures/Texture.cpp.s
.PHONY : src/Textures/Texture.s

# target to generate assembly for a file
src/Textures/Texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/Textures/Texture.cpp.s
.PHONY : src/Textures/Texture.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... imgui"
	@echo "... project"
	@echo "... src/Buffer/Buffer.o"
	@echo "... src/Buffer/Buffer.i"
	@echo "... src/Buffer/Buffer.s"
	@echo "... src/Global/Scene.o"
	@echo "... src/Global/Scene.i"
	@echo "... src/Global/Scene.s"
	@echo "... src/Meshes/ManualMesh.o"
	@echo "... src/Meshes/ManualMesh.i"
	@echo "... src/Meshes/ManualMesh.s"
	@echo "... src/Objects/Drawable.o"
	@echo "... src/Objects/Drawable.i"
	@echo "... src/Objects/Drawable.s"
	@echo "... src/Shaders/ShaderProgram.o"
	@echo "... src/Shaders/ShaderProgram.i"
	@echo "... src/Shaders/ShaderProgram.s"
	@echo "... src/Textures/FrameBuffer.o"
	@echo "... src/Textures/FrameBuffer.i"
	@echo "... src/Textures/FrameBuffer.s"
	@echo "... src/Textures/Texture.o"
	@echo "... src/Textures/Texture.i"
	@echo "... src/Textures/Texture.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

